export const ACTIONS = {
	ADD_TODO: 'ADD_TODO',
	DELETE_TODO: 'DELETE_TODO',
	TOGGLE_TODO: 'TOGGLE_TODO'
};

export const VISIBILITY_FILTERS = {
	SHOW_DONE: 'SHOW_DONE',
	SHOW_ALL: 'SHOW_ALL',
	SHOW_ACTIVE: 'SHOW_ACTIVE'
};