name: Check outdated PR

on:
  # pull_request:
  #   branches: [master]
  schedule:
    - cron: "*/5 * * * *"

jobs:
  check_outdated_pr:
    name: Check PR is up to date
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_OUTPUT
        id: date

      - name: Show current date
        run: echo "Current date is ${{ steps.date.outputs.NOW}}"

      - name: Show last pushed date
        run: |
          echo "Commits ${{ github.event.pull_request.commits }}"
          echo "Last updated date ${{ github.event.pull_request.updated_at }}"

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      # - if: ${{ github.event.repository.pushed_at != '' }}
      #   name: Set failure
      #   run: |
      #     echo "::error::Missing the library.package.json version bump. Run 'yarn workspace public-component-library version'"
      #     exit 1
